import test from "node:test";
import assert from "node:assert/strict";
import { ReminderStore } from "../src/store";
import {
  DEFAULT_MIRROR_FILE_PATH,
  DEFAULT_SETTINGS,
  type PluginData,
  type Reminder,
} from "../src/types";

test("markNotified records notification time without completing the reminder", async () => {
  const { store, getSaved } = await createStore();

  await store.markNotified("r1");

  const reminder = getSaved().reminders[0] as Reminder & { notifiedAt?: number };
  assert.equal(reminder.notified, true);
  assert.equal(reminder.completedAt, undefined);
  assert.equal(typeof reminder.notifiedAt, "number");
});

test("restore clears notification and completion timestamps", async () => {
  const { store, getSaved } = await createStore({
    notified: true,
    completedAt: 100,
    notifiedAt: 200,
  } as Reminder & { notifiedAt: number });

  await store.restore("r1");

  const reminder = getSaved().reminders[0] as Reminder & { notifiedAt?: number };
  assert.equal(reminder.notified, false);
  assert.equal(reminder.completedAt, undefined);
  assert.equal(reminder.notifiedAt, undefined);
});

test("hasPendingReminderForSourceTask only matches active linked reminders", async () => {
  const { store } = await createStore({ sourceTaskId: "task-1" });

  assert.equal(store.hasPendingReminderForSourceTask("task-1"), true);
  assert.equal(store.hasPendingReminderForSourceTask("task-2"), false);
});

test("hasPendingReminderForSourceTask ignores completed or notified reminders", async () => {
  const { store } = await createStore({
    sourceTaskId: "task-1",
    notified: true,
  });

  assert.equal(store.hasPendingReminderForSourceTask("task-1"), false);
});

test("writes hidden generated mirror files through the adapter when vault cache misses them", async () => {
  const writes: Array<{ path: string; data: string }> = [];
  const creates: Array<{ path: string; data: string }> = [];
  const files = new Map([
    [
      DEFAULT_MIRROR_FILE_PATH,
      [
        "# Reminders",
        "",
        "_Auto-generated by Quick Reminder plugin. Do not edit directly._",
        "",
        "## Pending",
        "",
        "_None._",
        "",
      ].join("\n"),
    ],
  ]);
  const { store } = await createStore(
    {},
    {
      app: createAppMock({ creates, files, writes }),
      settings: { mirrorToMarkdown: true },
    },
  );

  await store.add(
    createReminder({
      id: "r2",
      text: "call dad",
      rawInput: "call dad tomorrow",
    }),
  );

  const lastWrite = writes[writes.length - 1];
  assert.equal(lastWrite.path, DEFAULT_MIRROR_FILE_PATH);
  assert.match(lastWrite.data, /call dad/);
  assert.equal(creates.length, 0);
});

test("refuses hidden adapter mirror files that are not generated mirrors", async () => {
  const writes: Array<{ path: string; data: string }> = [];
  const creates: Array<{ path: string; data: string }> = [];
  const originalContent = "# Personal note\n\nDo not replace this.\n";
  const files = new Map([[DEFAULT_MIRROR_FILE_PATH, originalContent]]);
  const originalWarn = console.warn;
  console.warn = () => {};
  try {
    const { store } = await createStore(
      {},
      {
        app: createAppMock({ creates, files, writes }),
        settings: { mirrorToMarkdown: true },
      },
    );

    await store.add(
      createReminder({
        id: "r2",
        text: "call dad",
        rawInput: "call dad tomorrow",
      }),
    );
  } finally {
    console.warn = originalWarn;
  }

  assert.equal(files.get(DEFAULT_MIRROR_FILE_PATH), originalContent);
  assert.equal(writes.length, 0);
  assert.equal(creates.length, 0);
});

async function createStore(
  reminderPatch: Partial<Reminder> = {},
  options: {
    app?: ReturnType<typeof createAppMock>;
    settings?: Partial<PluginData["settings"]>;
  } = {},
) {
  let saved: PluginData | null = null;
  const reminder = createReminder(reminderPatch);
  const initialData: PluginData = {
    reminders: [reminder],
    settings: {
      ...DEFAULT_SETTINGS,
      mirrorToMarkdown: false,
      ...options.settings,
    },
  };
  const store = new ReminderStore(
    options.app ?? createAppMock(),
    async () => structuredClone(initialData),
    async (data) => {
      saved = structuredClone(data);
    },
  );

  await store.init();

  return {
    store,
    getSaved: () => {
      assert.ok(saved);
      return saved;
    },
  };
}

function createAppMock(
  options: {
    creates?: Array<{ path: string; data: string }>;
    files?: Map<string, string>;
    writes?: Array<{ path: string; data: string }>;
  } = {},
) {
  const files = options.files ?? new Map<string, string>();
  return {
    vault: {
      getAbstractFileByPath: () => null,
      createFolder: async () => {},
      create: async (path: string, data: string) => {
        options.creates?.push({ path, data });
        if (files.has(path)) {
          throw new Error("file already exists");
        }
        files.set(path, data);
        return {};
      },
      adapter: {
        exists: async (path: string) => files.has(path),
        read: async (path: string) => {
          const file = files.get(path);
          if (file === undefined) throw new Error("file not found");
          return file;
        },
        write: async (path: string, data: string) => {
          options.writes?.push({ path, data });
          files.set(path, data);
        },
        mkdir: async () => {},
      },
    },
  } as never;
}

function createReminder(patch: Partial<Reminder> = {}): Reminder {
  return {
    id: "r1",
    text: "call mom",
    rawInput: "call mom tomorrow",
    dueAt: Date.now() + 60_000,
    createdAt: Date.now(),
    notified: false,
    ...patch,
  };
}
