import test from "node:test";
import assert from "node:assert/strict";
import { ReminderStore } from "../src/store";
import {
  DEFAULT_MIRROR_FILE_PATH,
  DEFAULT_SETTINGS,
  type PluginData,
  type Reminder,
  type ScrapedTask,
} from "../src/types";

test("markNotified records notification time without completing the reminder", async () => {
  const { store, getSaved } = await createStore();

  await store.markNotified("r1");

  const reminder = getSaved().reminders[0] as Reminder & { notifiedAt?: number };
  assert.equal(reminder.notified, true);
  assert.equal(reminder.completedAt, undefined);
  assert.equal(typeof reminder.notifiedAt, "number");
});

test("restore clears notification and completion timestamps", async () => {
  const { store, getSaved } = await createStore({
    notified: true,
    completedAt: 100,
    notifiedAt: 200,
  } as Reminder & { notifiedAt: number });

  await store.restore("r1");

  const reminder = getSaved().reminders[0] as Reminder & { notifiedAt?: number };
  assert.equal(reminder.notified, false);
  assert.equal(reminder.completedAt, undefined);
  assert.equal(reminder.notifiedAt, undefined);
});

test("hasPendingReminderForSourceTask only matches active linked reminders", async () => {
  const { store } = await createStore({ sourceTaskId: "task-1" });

  assert.equal(store.hasPendingReminderForSourceTask("task-1"), true);
  assert.equal(store.hasPendingReminderForSourceTask("task-2"), false);
});

test("hasPendingReminderForSourceTask ignores completed or notified reminders", async () => {
  const { store } = await createStore({
    sourceTaskId: "task-1",
    notified: true,
  });

  assert.equal(store.hasPendingReminderForSourceTask("task-1"), false);
});

test("writes hidden generated mirror files through the adapter when vault cache misses them", async () => {
  const writes: Array<{ path: string; data: string }> = [];
  const creates: Array<{ path: string; data: string }> = [];
  const files = new Map([
    [
      DEFAULT_MIRROR_FILE_PATH,
      [
        "# Reminders",
        "",
        "_Auto-generated by Quick Reminder plugin. Do not edit directly._",
        "",
        "## Pending",
        "",
        "_None._",
        "",
      ].join("\n"),
    ],
  ]);
  const { store } = await createStore(
    {},
    {
      app: createAppMock({ creates, files, writes }),
      settings: { mirrorToMarkdown: true },
    },
  );

  await store.add(
    createReminder({
      id: "r2",
      text: "call dad",
      rawInput: "call dad tomorrow",
    }),
  );

  const lastWrite = writes[writes.length - 1];
  assert.equal(lastWrite.path, DEFAULT_MIRROR_FILE_PATH);
  assert.match(lastWrite.data, /call dad/);
  assert.equal(creates.length, 0);
});

test("refuses hidden adapter mirror files that are not generated mirrors", async () => {
  const writes: Array<{ path: string; data: string }> = [];
  const creates: Array<{ path: string; data: string }> = [];
  const originalContent = "# Personal note\n\nDo not replace this.\n";
  const files = new Map([[DEFAULT_MIRROR_FILE_PATH, originalContent]]);
  const originalWarn = console.warn;
  console.warn = () => {};
  try {
    const { store } = await createStore(
      {},
      {
        app: createAppMock({ creates, files, writes }),
        settings: { mirrorToMarkdown: true },
      },
    );

    await store.add(
      createReminder({
        id: "r2",
        text: "call dad",
        rawInput: "call dad tomorrow",
      }),
    );
  } finally {
    console.warn = originalWarn;
  }

  assert.equal(files.get(DEFAULT_MIRROR_FILE_PATH), originalContent);
  assert.equal(writes.length, 0);
  assert.equal(creates.length, 0);
});

test("snooze records the prior dueAt as snoozedFrom", async () => {
  const priorDueAt = 1_000_000;
  const { store, getSaved } = await createStore({ dueAt: priorDueAt });

  await store.snooze("r1", 10);

  const reminder = getSaved().reminders[0];
  assert.equal(reminder.snoozedFrom, priorDueAt);
  assert.equal(reminder.notified, false);
  assert.equal(reminder.notifiedAt, undefined);
  assert.equal(reminder.completedAt, undefined);
  assert.ok(reminder.dueAt > priorDueAt);
});

test("updateReminder clears provenance/timestamps and rebuilds rawInput", async () => {
  const { store, getSaved } = await createStore({
    notified: true,
    notifiedAt: 200,
    completedAt: 300,
    snoozedFrom: 400,
    rawInput: "old text yesterday",
  } as Reminder & { notifiedAt: number });

  // Local midnight keeps formatMachineDate deterministic across time zones.
  const newDue = new Date(2030, 0, 2, 9, 30).getTime();
  await store.updateReminder("r1", "buy milk", newDue);

  const reminder = getSaved().reminders[0] as Reminder & {
    notifiedAt?: number;
  };
  assert.equal(reminder.text, "buy milk");
  assert.equal(reminder.dueAt, newDue);
  assert.equal(reminder.rawInput, "buy milk 2030-01-02 09:30");
  assert.equal(reminder.notified, false);
  assert.equal(reminder.notifiedAt, undefined);
  assert.equal(reminder.completedAt, undefined);
  assert.equal(reminder.snoozedFrom, undefined);
});

test("relinkTask remaps reminder source, ignored id, and ignored note", async () => {
  const { store, getSaved } = await createStoreWithData({
    reminders: [createReminder({ sourceTaskId: "old-id" })],
    ignoredTaskIds: ["old-id"],
    ignoredTaskNotes: { "old-id": "later" },
    settings: { ...DEFAULT_SETTINGS, mirrorToMarkdown: false },
  });

  await store.relinkTask("old-id", "new-id");

  const saved = getSaved();
  assert.equal(saved.reminders[0].sourceTaskId, "new-id");
  assert.deepEqual(saved.ignoredTaskIds, ["new-id"]);
  assert.equal(saved.ignoredTaskNotes?.["new-id"], "later");
  assert.equal(saved.ignoredTaskNotes?.["old-id"], undefined);
});

test("relinkTask is a no-op when oldId equals newId", async () => {
  let saved: PluginData | null = null;
  const initialData: PluginData = {
    reminders: [createReminder({ sourceTaskId: "same-id" })],
    ignoredTaskIds: ["same-id"],
    ignoredTaskNotes: { "same-id": "later" },
    settings: { ...DEFAULT_SETTINGS, mirrorToMarkdown: false },
  };
  const store = new ReminderStore(
    createAppMock(),
    async () => structuredClone(initialData),
    async (data) => {
      saved = structuredClone(data);
    },
  );
  await store.init();

  await store.relinkTask("same-id", "same-id");

  // Early return -> no persist.
  assert.equal(saved, null);
});

test("relinkTaskReferences remaps via legacy-id map and migrates ignored notes", async () => {
  const { store, getSaved } = await createStoreWithData({
    reminders: [createReminder({ sourceTaskId: "legacy-task" })],
    ignoredTaskIds: ["legacy-ignored"],
    ignoredTaskNotes: { "legacy-ignored": "skip this one" },
    settings: { ...DEFAULT_SETTINGS, mirrorToMarkdown: false },
  });

  await store.relinkTaskReferences([
    createTask({ id: "task-new", legacyIds: ["legacy-task"] }),
    createTask({
      id: "ignored-new",
      legacyIds: ["legacy-ignored"],
      text: "ignored task",
    }),
  ]);

  const saved = getSaved();
  assert.equal(saved.reminders[0].sourceTaskId, "task-new");
  assert.deepEqual(saved.ignoredTaskIds, ["ignored-new"]);
  assert.equal(saved.ignoredTaskNotes?.["ignored-new"], "skip this one");
  assert.equal(saved.ignoredTaskNotes?.["legacy-ignored"], undefined);
});

test("relinkTaskReferences leaves a reminder whose sourceTaskId already matches a current task", async () => {
  let saved: PluginData | null = null;
  const initialData: PluginData = {
    reminders: [createReminder({ sourceTaskId: "task-current" })],
    ignoredTaskIds: [],
    ignoredTaskNotes: {},
    settings: { ...DEFAULT_SETTINGS, mirrorToMarkdown: false },
  };
  const store = new ReminderStore(
    createAppMock(),
    async () => structuredClone(initialData),
    async (data) => {
      saved = structuredClone(data);
    },
  );
  await store.init();

  // The reminder's sourceTaskId IS a current task id; the fuzzy fallback must
  // never run, so no persist happens (saved stays null) and the id is intact.
  await store.relinkTaskReferences([
    createTask({ id: "task-current", text: "call mom and dad about dinner" }),
  ]);

  assert.equal(saved, null);
});

test("relinkTaskReferences does not mislink a short reminder via substring text match", async () => {
  // Legacy id no longer resolves and has no legacyIds entry; the file holds a
  // task whose text merely CONTAINS the reminder text. Equality (not includes)
  // must prevent a mislink, so the stale sourceTaskId is left unchanged.
  let saved: PluginData | null = null;
  const initialData: PluginData = {
    reminders: [
      createReminder({
        text: "call mom",
        sourceTaskId: "Inbox.md:3:checkbox:call mom",
      }),
    ],
    ignoredTaskIds: [],
    ignoredTaskNotes: {},
    settings: { ...DEFAULT_SETTINGS, mirrorToMarkdown: false },
  };
  const store = new ReminderStore(
    createAppMock(),
    async () => structuredClone(initialData),
    async (data) => {
      saved = structuredClone(data);
    },
  );
  await store.init();

  await store.relinkTaskReferences([
    createTask({
      id: "task-longer",
      filePath: "Inbox.md",
      text: "call mom and dad about the trip",
    }),
  ]);

  // No exact-identity match -> no rebind -> nothing persisted.
  assert.equal(saved, null);
});

test("relinkTaskReferences rebinds a legacy reminder on exact whole-task identity", async () => {
  const { store, getSaved } = await createStoreWithData({
    reminders: [
      createReminder({
        text: "call mom",
        sourceTaskId: "Inbox.md:3:checkbox:call mom",
      }),
    ],
    ignoredTaskIds: [],
    ignoredTaskNotes: {},
    settings: { ...DEFAULT_SETTINGS, mirrorToMarkdown: false },
  });

  await store.relinkTaskReferences([
    createTask({ id: "task-exact", filePath: "Inbox.md", text: "call mom" }),
  ]);

  assert.equal(getSaved().reminders[0].sourceTaskId, "task-exact");
});

test("relinkTaskReferences bails when more than one task in the file matches", async () => {
  let saved: PluginData | null = null;
  const initialData: PluginData = {
    reminders: [
      createReminder({
        text: "call mom",
        sourceTaskId: "Inbox.md:3:checkbox:call mom",
      }),
    ],
    ignoredTaskIds: [],
    ignoredTaskNotes: {},
    settings: { ...DEFAULT_SETTINGS, mirrorToMarkdown: false },
  };
  const store = new ReminderStore(
    createAppMock(),
    async () => structuredClone(initialData),
    async (data) => {
      saved = structuredClone(data);
    },
  );
  await store.init();

  await store.relinkTaskReferences([
    createTask({ id: "task-a", filePath: "Inbox.md", text: "call mom" }),
    createTask({ id: "task-b", filePath: "Inbox.md", text: "call mom" }),
  ]);

  // Ambiguous (2 equal matches) -> bail rather than guess -> no persist.
  assert.equal(saved, null);
});

async function createStore(
  reminderPatch: Partial<Reminder> = {},
  options: {
    app?: ReturnType<typeof createAppMock>;
    settings?: Partial<PluginData["settings"]>;
  } = {},
) {
  let saved: PluginData | null = null;
  const reminder = createReminder(reminderPatch);
  const initialData: PluginData = {
    reminders: [reminder],
    settings: {
      ...DEFAULT_SETTINGS,
      mirrorToMarkdown: false,
      ...options.settings,
    },
  };
  const store = new ReminderStore(
    options.app ?? createAppMock(),
    async () => structuredClone(initialData),
    async (data) => {
      saved = structuredClone(data);
    },
  );

  await store.init();

  return {
    store,
    getSaved: () => {
      assert.ok(saved);
      return saved;
    },
  };
}

function createAppMock(
  options: {
    creates?: Array<{ path: string; data: string }>;
    files?: Map<string, string>;
    writes?: Array<{ path: string; data: string }>;
  } = {},
) {
  const files = options.files ?? new Map<string, string>();
  return {
    vault: {
      getAbstractFileByPath: () => null,
      createFolder: async () => {},
      create: async (path: string, data: string) => {
        options.creates?.push({ path, data });
        if (files.has(path)) {
          throw new Error("file already exists");
        }
        files.set(path, data);
        return {};
      },
      adapter: {
        exists: async (path: string) => files.has(path),
        read: async (path: string) => {
          const file = files.get(path);
          if (file === undefined) throw new Error("file not found");
          return file;
        },
        write: async (path: string, data: string) => {
          options.writes?.push({ path, data });
          files.set(path, data);
        },
        mkdir: async () => {},
      },
    },
  } as never;
}

function createReminder(patch: Partial<Reminder> = {}): Reminder {
  return {
    id: "r1",
    text: "call mom",
    rawInput: "call mom tomorrow",
    dueAt: Date.now() + 60_000,
    createdAt: Date.now(),
    notified: false,
    ...patch,
  };
}

async function createStoreWithData(initialData: PluginData) {
  let saved: PluginData | null = null;
  const store = new ReminderStore(
    createAppMock(),
    async () => structuredClone(initialData),
    async (data) => {
      saved = structuredClone(data);
    },
  );

  await store.init();

  return {
    store,
    getSaved: () => {
      assert.ok(saved);
      return saved;
    },
  };
}

function createTask(patch: Partial<ScrapedTask> = {}): ScrapedTask {
  return {
    id: "task-current",
    legacyIds: [],
    text: "call mom",
    contextNotes: [],
    contextNoteLines: [],
    filePath: "Inbox.md",
    line: 1,
    kind: "checkbox",
    status: "todo",
    completed: false,
    category: "",
    project: "",
    ...patch,
  };
}
