import { App, TFile, normalizePath } from "obsidian";
import { PluginData, Reminder, Settings, DEFAULT_SETTINGS } from "./types";

export class ReminderStore {
  private data: PluginData;
  private listeners: Set<() => void> = new Set();

  constructor(
    private app: App,
    private load: () => Promise<PluginData | null>,
    private save: (data: PluginData) => Promise<void>,
  ) {
    this.data = { reminders: [], settings: { ...DEFAULT_SETTINGS } };
  }

  onChange(fn: () => void): void {
    this.listeners.add(fn);
  }

  offChange(fn: () => void): void {
    this.listeners.delete(fn);
  }

  private notify(): void {
    for (const fn of this.listeners) {
      try {
        fn();
      } catch (e) {
        console.error("reminder listener failed", e);
      }
    }
  }

  async init(): Promise<void> {
    const loaded = await this.load();
    if (loaded) {
      this.data = {
        reminders: loaded.reminders ?? [],
        settings: { ...DEFAULT_SETTINGS, ...(loaded.settings ?? {}) },
      };
    }
  }

  get settings(): Settings {
    return this.data.settings;
  }

  get all(): Reminder[] {
    return [...this.data.reminders].sort((a, b) => a.dueAt - b.dueAt);
  }

  get pending(): Reminder[] {
    return this.all.filter((r) => !r.notified);
  }

  async add(reminder: Reminder): Promise<void> {
    this.data.reminders.push(reminder);
    await this.persist();
  }

  async markNotified(id: string): Promise<void> {
    const r = this.data.reminders.find((x) => x.id === id);
    if (!r) return;
    r.notified = true;
    r.completedAt = Date.now();
    await this.persist();
  }

  async complete(id: string): Promise<void> {
    const r = this.data.reminders.find((x) => x.id === id);
    if (!r) return;
    r.notified = true;
    r.completedAt = Date.now();
    await this.persist();
  }

  async restore(id: string): Promise<void> {
    const r = this.data.reminders.find((x) => x.id === id);
    if (!r) return;
    r.notified = false;
    delete r.completedAt;
    await this.persist();
  }

  async updateReminder(id: string, text: string, dueAt: number): Promise<void> {
    const r = this.data.reminders.find((x) => x.id === id);
    if (!r) return;
    r.text = text;
    r.rawInput = `${text} ${new Date(dueAt).toLocaleString()}`;
    r.dueAt = dueAt;
    r.notified = false;
    delete r.completedAt;
    await this.persist();
  }

  async snooze(id: string, minutes: number): Promise<void> {
    const r = this.data.reminders.find((x) => x.id === id);
    if (!r) return;
    r.snoozedFrom = r.dueAt;
    r.dueAt = Date.now() + minutes * 60_000;
    r.notified = false;
    delete r.completedAt;
    await this.persist();
  }

  async remove(id: string): Promise<void> {
    this.data.reminders = this.data.reminders.filter((r) => r.id !== id);
    await this.persist();
  }

  async updateSettings(patch: Partial<Settings>): Promise<void> {
    this.data.settings = { ...this.data.settings, ...patch };
    await this.persist();
  }

  private async persist(): Promise<void> {
    await this.save(this.data);
    if (this.data.settings.mirrorToMarkdown) {
      await this.mirrorToMarkdown().catch((e) => console.error("mirror failed", e));
    }
    this.notify();
  }

  private async mirrorToMarkdown(): Promise<void> {
    const path = normalizePath(this.data.settings.mirrorFilePath);
    const body = this.renderMarkdown();
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof TFile) {
      await this.app.vault.modify(existing, body);
    } else {
      await this.app.vault.create(path, body);
    }
  }

  private renderMarkdown(): string {
    const lines: string[] = ["# Reminders", "", "_Auto-generated by Quick Reminder plugin. Do not edit directly._", ""];
    const pending = this.pending;
    const done = this.all.filter((r) => r.notified);

    lines.push("## Pending", "");
    if (pending.length === 0) {
      lines.push("_None._", "");
    } else {
      for (const r of pending) {
        lines.push(`- [ ] ${r.text} — **${formatDate(r.dueAt)}**`);
      }
      lines.push("");
    }

    lines.push("## Notified", "");
    if (done.length === 0) {
      lines.push("_None._", "");
    } else {
      for (const r of done.slice(-20).reverse()) {
        lines.push(`- [x] ${r.text} — ${formatDate(r.dueAt)}`);
      }
    }

    return lines.join("\n");
  }
}

function formatDate(ms: number): string {
  const d = new Date(ms);
  return d.toLocaleString(undefined, {
    weekday: "short",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}
